POST  http://localhost:5000/users
Content-Type: application/json

{
      "name": "bimouser",
    "email": "user@gmail.com",
    "password": "12345",
    "confPassword":"12345",
    "role":"admin"
}

###
GET http://localhost:5000/karyawan


###
POST http://localhost:5000/cabang
Content-Type: application/json

{
    "kode_cabang": "02",
    "nama_cabang": "testcabang",
    "latitude": -7.0036053,
    "longitude": 110.4515652,
    "radius": 100
}

###
PUT http://localhost:5000/cabang/3
Content-Type: application/json

{
"kode_cabang": "02",
"nama_cabang": "testcabang",
"lokasi_kantor": "-7.0036053,110.4515652",
"radius": "100"
}

###
GET  http://localhost:5000/cabang

###
PUT  http://localhost:5000/cabang/2
Content-Type: application/json

{
    "kode_cabang": "02",
    "nama_cabang": "Cabang Baru",
    "latitude": "-7.0036053",
    "longitude": "110.4515652",
    "radius": 100
}

###
POST http://localhost:5000/department
Content-Type: application/json

{
     "kode_department": "111",
      "nama_department": "test"
}


###
POST  http://localhost:5000/karyawan/
Content-Type: application/json

{
            "nik":"3333333333",
            "nama_lengkap" : "testmidleware",
            "jabatan" : "test",
            "DepartmentId": "1",
            "CabangId": "2",
            "no_telp": "1234567890",
            "avatar": "",
            "password": "test123"
}



###
PUT  http://localhost:5000/karyawan/2
Content-Type: application/json

{
            "nik":"2222222222",
            "nama_lengkap" : "testjammasukkeluar",
            "jabatan" : "test",
            "DepartmentId": 1,
            "CabangId": 2,
            "no_telp": "1234567890",
            "avatar": "",
            "password": "test123"
}

###
PUT  http://localhost:5000/karyawan/2
Content-Type: application/json

{
            "nik":"2222222222",
            "nama_lengkap" : "testjammasukkeluar",
            "jabatan" : "test",
            "no_telp": "12345611",
            "avatar": "",
            "password": "test123"
}
###
PUT  http://localhost:5000/karyawan/2
Content-Type: application/json

{
            "DepartmentId": 1,
            "CabangId": 2
          
}
###
GET  http://localhost:5000/karyawan/1


###
GET http://localhost:5000/department/1


###
GET  http://localhost:5000/cabang

###
GET  http://localhost:5000/admin/jamKerja

###
POST  http://localhost:5000/admin/jamKerja
Content-Type: application/json

{
      "kode_jamKerja" : "01",
      "nama_jamKerja" : "Test",
      "awal_jamMasuk" : "00:00:00",
      "set_jamMasuk" : "01:00:00",
      "akhir_jamMasuk" : "07:00:00",
      "set_jamPulang" : "15:00:00"
}

###
PUT  http://localhost:5000/admin/jamKerja/1
Content-Type: application/json

{
      "kode_jamKerja" : "01",
      "nama_jamKerja" : "Test",
      "awal_jamMasuk" : "00:00:00",
      "set_jamMasuk" : "01:00:00",
      "akhir_jamMasuk" : "23:58:00",
      "set_jamPulang" : "23:59:00"
}

###
POST  http://localhost:5000/set
Content-Type: application/json

{
    
    "karyawan_id": 2,
    "jam_id": "2",
    "hari": "selasa"
}

###
POST http://localhost:5000/sethari
Content-Type: application/json

{
    
    "karyawan_id": 2,
    "jam_id": "2",
    "hari": "Kamis"

}

###
POST  http://localhost:5000/izin
Content-Type: application/json

{
    
    "tgl_izin": "2024-03-24",
    "status": "i",
    "keterangan": "test",
    "status_approved":"0",
    "foto":"",
    "KaryawanId":"1"

}

###
POST http://localhost:5000/loginAdmin
Content-Type: application/json

{
      "email": "user@gmail.com",
      "password": "12345"
}

###
GET  http://localhost:5000/Me

###
DELETE http://localhost:5000/logoutAdmin


###
POST http://localhost:5000/loginKaryawan
Content-Type: application/json

{
      "nik": "1111111111",
      "password": "test123"
}

###
POST http://localhost:5000/loginKaryawan
Content-Type: application/json

{
      "nik": "2222222222",
      "password": "test123"
}


###
GET http://localhost:5000/MeKaryawan

###
DELETE  http://localhost:5000/logoutKaryawan


###
POST http://localhost:5000/absensi/karyawan/create
Content-Type: application/json

{
   
   "latitude": -7.0036053,
    "longitude": 110.4515652,
   "image": "data:image/png;base64,iVBORw"
} 

###
GET  http://localhost:5000/absensi/get


###
PUT  http://localhost:5000/absensi/karyawan/keluar
Content-Type: application/json

{
   
   "latitude": -7.003053,
   "longitude": 110.4515652,
   "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABqUlEQVR4nGNgGAWjYBSMglEw1ZIExUQtQJL"

}

###
POST  http://localhost:5000/absensi/karyawan/create
Content-Type: application/json

{
    "latitude": -7.0036053,
    "longitude": 110.4515652,
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABqUlEQVR4nGNgGAWjYBSMglEw1ZIExUQtQJL"
}
//keluar

###
PUT http://localhost:5000/absensi/karyawan/keluar
Content-Type: application/json

{
  
   
   "latitude": -7.0036053,
    "longitude": 110.4515652,
   "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAIAAAAC64paAAABqUlEQVR4nGNgGAWjYBSMglEw1ZIExUQtQJL"
}



###
GET http://localhost:5000/absensibulanini/get?bulan=04&tahun=2024



###
GET  http://localhost:5000/absensitotal/get?bulan=04&tahun=2024


//praktikum

###
GET https://api.rajaongkir.com/starter/province?id=2
key: 977196c317e8371d55e5d2a680fd06d7
###
GET https://api.rajaongkir.com/starter/province/
key: 977196c317e8371d55e5d2a680fd06d7

###
GET https://api.rajaongkir.com/starter/city
key: 977196c317e8371d55e5d2a680fd06d7
###
GET https://api.rajaongkir.com/starter/city?id=2
key: 977196c317e8371d55e5d2a680fd06d7

###
POST https://api.rajaongkir.com/starter/cost
key: 977196c317e8371d55e5d2a680fd06d7
Content-Type: application/json

{
    "origin" : "501",

    "destination": "114",

    "weight": "1700",

    "courier": "jne"
}